services:
  mysql:
    image: mysql:8.0
    container_name: mysql_organize_my_mind
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: organize_my_mind
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

  api:
    build: .
    container_name: api_organize_my_mind
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: organize_my_mind
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    command: ["bun", "run", "start:dev"]

volumes:
  mysql_data:
