services:
  db:
    image: mysql:latest
    container_name: organize_my_mind
    restart: always
    environment:
     MYSQL_DATABASE: organize_my_mind
     MYSQL_USER: user
     MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

  api:
    build:
      context: ./api-organize-my-mind
      dockerfile: Dockerfile
    container_name: api_organize_my_mind
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_NAME: organize_my_mind
    ports:
      - "3000:3000"
    volumes:
      - ./api-organize-my-mind:/app
      - /app/node_modules
    command: >
      sh -c "pnpm start:dev"

volumes:
  mysql_data:
